### ISSUE TITLE
"nd_patch_step" variable is not define

### ISSUE THREAD

**Issue by mshahabi** [khalooei/ALOCC-CVPR2018#19]
Hello there,

In your "test.py" file the variable "nd_patch_step" is not defined. If I track down the variable it should be equal to "nStride", but with such setting the test does not seem to be working correct.

Am I missing some thing?

Thanks

**Comment by khalooei** [comment]
Dear @mshahabi , 
I'm so sorry for the late reply because of my busy time in these days.
Yes, as you said, the nd_patch_step is like as below:
`
    nd_patch_step = (n_stride, n_stride)
`
Also, you can use any other configuration, and it is not related to the main idea. I try to update this project if I have much time in near future.

Best regards,
Mohammad
