### ISSUE TITLE
Something about the test.py file

### ISSUE THREAD

**Issue by liulonghoi** [khalooei/ALOCC-CVPR2018#21]
Hello, I change the dataset for my own dataset, and the test.py file run well, but i dont kown how this file work, could you tell me what does this file do? How to use a trained model? Thanks in advance!

**Comment by codeman008** [comment]
Hello, I am also doing single-type image detection recently. How do you train your data?Thank you very much

**Comment by khalooei** [comment]
Dear @liulonghoi and @codeman008 , I'm so sorry for late reply because I'm busy right now. 
> 
> Hello, I change the dataset for my own dataset, and the test.py file run well, but i dont kown how this file work, could you tell me what does this file do? How to use a trained model? Thanks in advance!
> 
> Hello, I am also doing single-type image detection recently. How do you train your data?Thank you very much


To use our approach in new dataset, you can just change the modification which related to your dataset. You must check your normalization step, you must check your inputs and etc. Therefore, you can trace the entrance of your model configuration and check each section in training and test phase. You can customize it in different dataset and settings. This work is used in some industrial company in real data in previous years.
