### ISSUE TITLE
generator outputs minus values

### ISSUE THREAD

**Issue by hhachiya** [khalooei/ALOCC-CVPR2018#3]
https://github.com/khalooei/ALOCC-CVPR2018/blob/9fd544d7ac32b04cb4c8d32fdc6b60e1016b074b/models.py#L370

Hi, the output values of generator G is the one of tanh and thus it takes [-1,1] values.
But the true input takes [0,1] values (at least, MNIST case).
Thus, it will be too easy for discriminator D to classify True or False, by just checking if minus values being contained.  The output of G should take sigmoid instead of tanh?

**Comment by khalooei** [comment]
Dear @hhachiya 

Thanks for your feedback. In our setting, after training, R network refines its input. We aimed to put the outputs of R open with a wider range (using tanh) and not restrict it as sigmoid does. This let D to decide and map to 0 or 1. But it is also possible to return the deconv feature map of the last layer (h4) without  applying any functions. Therefore, we suggest not using  sigmoid because of its restricted range.

Best regards,
Mohammad khalooei
